/*
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

module.exports = (args) => {
	let firstFib = 1, secondFib = 2, sum = 2;
	const n = args[0] || 4000000;

	for (let i = 3; i < n; i = firstFib + secondFib){
		if (i % 2 == 0)
			sum += i;

		firstFib = secondFib;
		secondFib = i;
	}

	console.log(`The sum of the even-valued terms whose values do not exceed ${n} ${sum}`);

	return sum;
}